### ISSUE TITLE
better-log show NaN passing when test on mocha

### ISSUE THREAD

**Issue by cmoon2000** [RReverser/better-log#2]
When using mocha it show NaN

![screenshot_2015-07-23_09-27-09](https://cloud.githubusercontent.com/assets/6170794/8841847/2406ce36-311d-11e5-8c25-0666efc17bab.png)

**Comment by RReverser** [comment]
Does it show correct number with better-log being disabled?

**Comment by cmoon2000** [comment]
When I disable like `README`, at the end, now it works fine.

> require('better-log').uninstall();
> Does it have any fix or else because It comes with unconvinient quite?

**Comment by RReverser** [comment]
>  Does it have any fix or else because It comes with unconvinient quite?

Please describe what you mean more precisely. I'm not following.

**Comment by cmoon2000** [comment]
To avoid `NaN` I have to disable `better-log` each file test. It will better that We never worry about disabling.

**Comment by RReverser** [comment]
I'll try to look into it as soon as I find time, but it would be very helpful if you could do that (basically, just look into the Mocha code and figure out what type of number it tries to submit that might cause this).

**Comment by RReverser** [comment]
I think I've found and fixed potential cause of this, although not sure - please check out the new version and let me know whether it works now.

**Comment by cmoon2000** [comment]
Now It can show number. Except a little change in color
**Original**
![original](https://cloud.githubusercontent.com/assets/6170794/8889749/3e2e6184-3311-11e5-8cd4-c9eb825ec5e3.png)

**Use better-log**
![other](https://cloud.githubusercontent.com/assets/6170794/8889754/603b91ac-3311-11e5-858d-e9e647de6986.png)

**Comment by RReverser** [comment]
Well, yes - numbers have different color in output, that's the entire idea of better-log :)

**Comment by RReverser** [comment]
However, need to think about this more. Not sure how to detect and in which cases is better to use originally formatted string than format on behalf of better-log.

**Comment by RReverser** [comment]
Btw, for your case the easier might be to use better-log not as replacement for `console.log` but as module on its own (see example in README). In that case, you will be able to call `betterLog(...)` for whatever you need while Mocha will use built-in one.

**Comment by cmoon2000** [comment]
yes. It's not easy to make it work totally well with other modules. A combine between mocha and better-log like above still be good to me.

And I also tried your guess with `Manual usage as a regular function`. But I meet another issue:

> var log = require('better-log');
> log({ x: 1, y: 'prop' }); // it shows: undefined
> log.error('Something bad happened :(');

**Comment by RReverser** [comment]
Ah right, that was broken by previous fix :) Thanks for reporting, should be fixed now and also added basic hook-based tests.

**Comment by cmoon2000** [comment]
yes. I'm so happy for reporting
